server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/benfill/AssureTech.git
          default-label: main
          search-paths: configs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/