version: '3.8'

services:
  client-service:
    build: .
    container_name: client-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/ClientDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15
    container_name: Client-DB
    restart: always
    environment:
      POSTGRES_DB: ClientDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
